steps:
- id: docker build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/builder-quarkus', './builder-image/Dockerfile']
images:
- 'europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/builder-quarkus'
options:
  machineType: E2_HIGHCPU_32
