steps:
- id: Compile native app
  name: 'europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/builder-quarkus'
  args: ['package', '-Pnative', '-Dquarkus.container-image.build=true']
  env:
    - 'quarkus.container-image.name=europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/quarkus-demo-rest'
images:
- 'quarkus.container-image.name=europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/quarkus-demo-rest'
options:
  machineType: E2_HIGHCPU_32
