steps:
- id: Compile native app
  name: 'europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/builder-quarkus'
  args: ['package', '-f','./quarkus-rest-app/pom.xml','-Pnative', '-Dquarkus.container-image.build=true']
  env:
    - 'quarkus.container-image.name=europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/quarkus-demo-rest'
- id: Build native docker image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/quarkus-demo-rest','-f', 'quarkus-rest-app/src/main/docker/Dockerfile.native','./quarkus-rest-app']
images:
- 'quarkus.container-image.name=europe-west2-docker.pkg.dev/meta-yen-311209/docker-registry/quarkus-demo-rest'
options:
  machineType: E2_HIGHCPU_32
